### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by nbibler** [IvyApp/ivy-videojs#10]
VideoJS "ships" with language support. They distribute the languages with their Bower build, but each language is a separate JavaScript file under `dist/lang/ID.js`. In order to use their official languages, each desired language must be loaded.

So the question (more than issue) is what is the "official" way to get language support with ivy-videojs? Since `video.js` is a Bower sub-dependency, it seems odd that a project using it would reach down to a 2nd level dependency to pull the dist files (or that they should know to do that). Should ivy-videojs provide those languages as 1st level dependencies? Should the official stance be that apps that want language support must add a new Bower dependency to their project to have 1st level access to those language files?

**Comment by nbibler** [comment]
The following changes added Spanish language support to the dummy app, for example:

```diff
diff --git ember-cli-build.js ember-cli-build.js
index 570d8d9..a9bf8f4 100644
--- ember-cli-build.js
+++ ember-cli-build.js
@@ -19,6 +19,8 @@ module.exports = function(defaults) {
     type: 'test'
   });
 
+  app.import(path.join(app.bowerDirectory, 'video.js/dist/lang/es.js'));
+
   var bootstrapTree = pickFiles(path.join(app.bowerDirectory, 'bootstrap/dist/css'), {
     srcDir: '/',
     destDir: '/assets'
diff --git tests/dummy/app/index.html tests/dummy/app/index.html
index 754c61f..ffe117e 100644
--- tests/dummy/app/index.html
+++ tests/dummy/app/index.html
@@ -1,5 +1,5 @@
 <!DOCTYPE html>
-<html>
+<html lang="es">
   <head>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
```

**Comment by omghax** [comment]
I had to do [something similar](https://github.com/IvyApp/ivy-codemirror/blob/master/index.js#L19-L29) in `ivy-codemirror`. There I provided some options that could be passed to the ember-cli app inside `ember-cli-build.js`.

**Comment by omghax** [comment]
I've added a `videojs` configuration option you can specify in `ember-cli-build.js`:

```js
  var app = new EmberApp(defaults, {
    videojs: {
      languages: ['es']
    }
  });
```

Then you can specify `language` on the `ivy-videojs` component:

```handlebars
{{ivy-videojs language="es"}}
```
