### ISSUE TITLE
Passing properties to <video> element

### ISSUE THREAD

**Issue by devlo** [IvyApp/ivy-videojs#11]
``{{ivy-videojs src=src preload="auto" autoplay=true}}``

autoplay and preload are not passed to <video> element

**Comment by ChaseGiunta** [comment]
@devlo did you figure this out? Is autoplay not supported?

**Comment by devlo** [comment]
component.bindPropertyToPlayer(player, 'autoplay');

**Comment by ben-rabid** [comment]
@ChaseGiunta: There appears to be a bug in the library for `autoplay` - can you have a look at https://github.com/IvyApp/ivy-videojs/pull/17 and see if it fixes your issue?
