### ISSUE TITLE
Source to the demo app?

### ISSUE THREAD

**Issue by eggfriedrice** [IvyApp/ivy-videojs#13]
Hi

I'm playing with this now and it looks great but there are a few things I don't quite get.

It would be really useful to see the source to the demo app (http://ivyapp.github.io/ivy-videojs/). Is that source available somewhere, or could it be?

Cheers,
Al

**Comment by omghax** [comment]
Take a look at [`tests/dummy`](https://github.com/IvyApp/ivy-videojs/tree/master/tests/dummy). That's the demo app, which is also what is served if you clone this repo, run `ember serve`, and visit [localhost:4200](http://localhost:4200). Most of the code for the demo app is in [`app/controllers/index.js`](https://github.com/IvyApp/ivy-videojs/blob/master/tests/dummy/app/controllers/index.js), and its corresponding [`index.hbs`](https://github.com/IvyApp/ivy-videojs/blob/master/tests/dummy/app/templates/index.hbs) template. Hopefully that gives you a decent idea of how everything ties together. Happy hacking!

**Comment by eggfriedrice** [comment]
Aha! Thanks for pointing it out, that'll help, though I think I've worked out most of what I was struggling with. Ta!
