### ISSUE TITLE
Compatible with Glimmer

### ISSUE THREAD

**Issue by inDream** [IvyApp/ivy-videojs#3]
To compatible with Glimmer
https://github.com/IvyApp/ivy-videojs/blob/master/addon/components/ivy-videojs.js#L64
Need to change to `if (property in this || property in this.attrs) {`
This is only a note for people want to test Glimmer,
I think we should wait for the official blog.

**Comment by omghax** [comment]
Thanks for looking into this :)

Rather than trying to support both pre- and post-Glimmer Ember versions, I decided to just drop the conditional. It doesn't change the behavior at all, it was just there as a performance optimization.
