### ISSUE TITLE
element error

### ISSUE THREAD

**Issue by iamalex2** [IvyApp/ivy-videojs#8]
I have a video set like in example:
autoresize=true naturalWidth=1280 naturalHeight=720
which is actual size but getting the error below.
Even if I take the size off and leave at autoresize=true still get an error.

VIDEOJS: ERROR: Improper value "NaN" supplied for for height

Can anyone help?

**Comment by omghax** [comment]
I just pushed version 0.6.0 which actually drops `autoresize` in favor of using VideoJS's built-in `fluid` setting. Here's an example:

```handlebars
{{ivy-videojs fluid=true src="video.mp4"}}
```

Note that 0.6.0 is a breaking change, so give UPGRADING.md a look. Let me know if you run into any other issues that should be documented there. Thanks!
